alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias ll='ls -alF'
alias la='ls -AF'
alias l='ls -F'

alias cls='clear'
alias cll='cls;ll'

alias qq='exit'

alias ..='cd ..'
alias ...='cd ../..'

alias apt-upd='sudo apt-get update'
alias apt-cls='sudo apt autoremove && sudo apt autoclean'
alias apt-upg='apt-upd && sudo apt-get upgrade -y && apt-cls'
