- hosts: all
  become: true
  remote_user: "{{ ansible_username }}"
  pre_tasks:
    - name: update cache
      apt:
        update_cache: true
      changed_when: false
  roles:
    - common

- hosts: linux_servers
  become: true
  remote_user: "{{ ansible_username }}"
  roles:
    - linux_server
    - docker_host
    - local_dns
    - reverse_proxy
    - portainer_manager
    - cloudflare_connector
    - code_server
