- hosts: linux_servers
  become: true
  remote_user: "{{ ansible_username }}"
  tasks:
    - name: remove all services
      ansible.builtin.include_role:
        name: "{{ role }}"
        tasks_from: cleanup.yml
      loop:
        - cloudflare_connector
        - portainer
        - reverse_proxy
        - local_dns
      loop_control:
        loop_var: role
