- name: create media directories
  ansible.builtin.file:
    path: "{{ item.0 }}/media/{{ item.1 }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_nested:
    - "{{ directories | dict2items
         | selectattr('key', 'match', '^media(_.*)?$')
         | map(attribute='value')
         | list }}"
    - [ "anime", "movies", "tv" ]

- name: create download directories
  ansible.builtin.file:
    path: "{{ directories.media_1 }}/downloads/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  loop:
    - torrents/complete
    - torrents/incomplete
    - youtube

- name: create media server directory
  ansible.builtin.file:
    path: "{{ directories.services }}/media-server"
    state: directory
    owner: "{{ main_user.name }}"
    group: "{{ main_user.name }}"
    mode: 0755

- name: deploy media server from template file
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ directories.services }}/media-server/docker-compose.yml"
    owner: "{{ main_user.name }}"
    group: "{{ main_user.name }}"
    mode: 0644

- name: run media server using docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ directories.services }}/media-server"
