- name: install unattended-upgrades and needrestart
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - needrestart
    state: present
    update_cache: yes

- name: configure unattended-upgrades
  ansible.builtin.template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
  notify: restart_unattended_upgrades

- name: enable automatic updates
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: yes
    state: started
