- name: setup grafana stack directory
  ansible.builtin.file:
    path: "{{ directories.services }}/grafana"
    state: directory
    owner: "{{ main_user.name }}"
    group: "{{ main_user.name }}"
    mode: 0755

- name: deploy grafana stack from template files
  ansible.builtin.template:
    src: "templates/{{ filename }}.j2"
    dest: "{{ directories.services }}/grafana/{{ filename }}"
    owner: "{{ main_user.name }}"
    group: "{{ main_user.name }}"
    mode: 0644
  loop:
    - config.alloy
    - Dockerfile.alloy
    - datasources.yaml
    - Dockerfile.grafana
    - docker-compose.yml
  loop_control:
    loop_var: filename

- name: run grafana stack using docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ directories.services }}/grafana"
    build: always
