- name: setup grafana stack directory
  ansible.builtin.file:
    path: "{{ directories.services }}/grafana/{{ dirname }}"
    state: directory
    owner: "{{ main_user.name }}"
    group: "{{ main_user.name }}"
    mode: 0755
  loop:
    - alloy
    - grafana
    - loki
    - prometheus
  loop_control:
    loop_var: dirname

- name: deploy grafana stack from template files
  ansible.builtin.template:
    src: "templates/{{ filename }}.j2"
    dest: "{{ directories.services }}/grafana/{{ filename }}"
    owner: "{{ main_user.name }}"
    group: "{{ main_user.name }}"
    mode: 0644
  loop:
    - alloy/config.alloy
    - alloy/Dockerfile
    - grafana/datasources.yaml
    - grafana/Dockerfile
    - loki/loki-config.yaml
    - loki/Dockerfile
    - prometheus/prometheus.yml
    - prometheus/Dockerfile
    - docker-compose.yml
  loop_control:
    loop_var: filename

- name: run grafana stack using docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ directories.services }}/grafana"
    build: always
