- name: setup gluetun directory
  ansible.builtin.file:
    path: "{{ directories.services }}/gluetun"
    state: directory
    owner: "{{ main_user.name }}"
    group: "{{ main_user.name }}"
    mode: 0755

- name: deploy gluetun from template file
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ directories.services }}/gluetun/docker-compose.yml"
    owner: "{{ main_user.name }}"
    group: "{{ main_user.name }}"
    mode: 0644

- name: run gluetun using docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ directories.services }}/gluetun"
