umask: '002'

media_services:
  - name: plex
    version: release-1.42.1.10060-4e8b05daf
    host: "{{ vault_plex_host }}"
    port: "{{ vault_plex_port }}"
    advertise_url: "{{ vault_plex_advertise_url }}"
    claim_token: "{{ vault_plex_claim_token }}"
    homepage:
      title: Plex
      description: Media Server
      icon: /icons/plex.png
      key: "{{ vault_plex_auth_token }}"
      fields: ["streams", "movies", "tv"]
      group: Media
      order: 1
  - name: radarr
    version: release-5.27.5.10198
    host: "{{ vault_radarr_host }}"
    port: "{{ vault_radarr_port }}"
    homepage:
      title: Radarr
      description: Movies Manager
      icon: /icons/radarr.png
      key: "{{ vault_radarr_api_key }}"
      public: true
      group: Media
      order: 2
  - name: sonarr
    version: release-4.0.15.2941
    host: "{{ vault_sonarr_host }}"
    port: "{{ vault_sonarr_port }}"
    homepage:
      title: Sonarr
      description: TV Manager
      icon: /icons/sonarr.png
      key: "{{ vault_sonarr_api_key }}"
      public: true
      group: Media
      order: 3
  - name: bazarr
    version: release-1.5.2
    host: "{{ vault_bazarr_host }}"
    port: "{{ vault_bazarr_port }}"
    homepage:
      title: Bazarr
      description: Subtitles Manager
      icon: /icons/bazarr.png
      key: "{{ vault_bazarr_api_key }}"
      group: Media
      order: 4
