umask: '002'

media_data_path: "{{ directories.media }}"

media_services:
  - name: plex
    version: release-1.42.1.10054-f333bdaa8
    host: "{{ vault_plex_host }}"
    port: "{{ vault_plex_port }}"
    advertise_url: "{{ vault_plex_advertise_url }}"
    claim_token: "{{ vault_plex_claim_token }}"
    homepage:
      title: Plex
      description: Media Server
      icon: /icons/plex.png
      group: Media
      order: 1
      fields: ["streams", "movies", "tv"]
      key: "{{ vault_plex_auth_token }}"
  - name: qbittorrent
    version: release-5.1.2
    host: "{{ vault_qbittorrent_host }}"
    port: "{{ vault_qbittorrent_port }}"
    homepage:
      title: qBittorrent
      description: Torrent Client
      icon: /icons/qbittorrent.png
      group: Download
      order: 1
      username: "{{ vault_qbittorrent_username }}"
      password: "{{ vault_qbittorrent_password }}"
  - name: radarr
    version: nightly-5.27.4.10154
    host: "{{ vault_radarr_host }}"
    port: "{{ vault_radarr_port }}"
    homepage:
      title: Radarr
      description: Movies Manager
      icon: /icons/radarr.png
      group: Media
      order: 2
      key: "{{ vault_radarr_api_key }}"
  - name: sonarr
    version: release-4.0.15.2941
    host: "{{ vault_sonarr_host }}"
    port: "{{ vault_sonarr_port }}"
    homepage:
      title: Sonarr
      description: TV Manager
      icon: /icons/sonarr.png
      group: Media
      order: 3
      key: "{{ vault_sonarr_api_key }}"
  - name: bazarr
    version: nightly-873b444
    host: "{{ vault_bazarr_host }}"
    port: "{{ vault_bazarr_port }}"
    homepage:
      title: Bazarr
      description: Subtitles Manager
      icon: /icons/bazarr.png
      group: Media
      order: 4
      key: "{{ vault_bazarr_api_key }}"
  - name: prowlarr
    version: release-1.37.0.5076
    host: "{{ vault_prowlarr_host }}"
    port: "{{ vault_prowlarr_port }}"
    homepage:
      title: Prowlarr
      description: Indexer Manager
      icon: /icons/prowlarr.png
      group: Download
      order: 2
      key: "{{ vault_prowlarr_api_key }}"
