- name: stop and disable docker backup timer
  systemd:
    name: docker-backup.timer
    enabled: no
    state: stopped

- name: stop docker backup service
  systemd:
    name: docker-backup.service
    state: stopped

- name: remove docker backup service file
  ansible.builtin.file:
    path: /etc/systemd/system/docker-backup.service
    state: absent

- name: remove docker backup timer file
  ansible.builtin.file:
    path: /etc/systemd/system/docker-backup.timer
    state: absent

- name: reload systemd daemon
  systemd:
    daemon_reload: yes

- name: remove scripts and helper files
  ansible.builtin.file:
    path: "{{ directories.scripts }}/{{ rel_path }}"
    state: absent
  loop:
    - docker_volumes_backup.sh
    - docker_volumes_restore.sh
    - shared/docker_helpers.sh
    - shared/exclude_volumes.txt
  loop_control:
    loop_var: rel_path

- name: remove alpine image
  community.docker.docker_image:
    name: alpine
    state: absent
