- name: stop and disable docker backup service and timer
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - docker-backup.timer
    - docker-backup.service
  ignore_errors: true

- name: remove docker backup files (service, timer, scripts)
  ansible.builtin.file:
    path: "{{ path }}"
    state: absent
  loop:
    - /etc/systemd/system/docker-backup.timer
    - /etc/systemd/system/docker-backup.service
    - /etc/docker-backup.conf
    - "{{ directories.scripts }}/docker_volumes_backup.sh"
    - "{{ directories.scripts }}/docker_volumes_restore.sh"
    - "{{ directories.scripts }}/shared/docker_helpers.sh"
  loop_control:
    loop_var: path

- name: reload systemd daemon
  systemd:
    daemon_reload: yes

- name: remove alpine image
  community.docker.docker_image:
    name: alpine
    state: absent
