- name: ensure backup volumes directory exists
  ansible.builtin.file:
    path: "{{ backup_volumes_dir }}"
    state: directory
    owner: "{{ main_user.name }}"
    group: "{{ main_user.name }}"
    mode: 0755

- name: deploy docker backup config
  ansible.builtin.copy:
    dest: /etc/docker-backup.conf
    content: |
      BACKUP_VOLUMES_DIR={{ backup_volumes_dir }}
      RETENTION_DAYS={{ backup_retention_period }}
      {% if backup_exclude_volumes is defined and backup_exclude_volumes | length > 0 %}EXCLUDE_VOLUMES="{{ backup_exclude_volumes | join(' ') }}"{% endif %}
    owner: root
    group: root
    mode: 0644

- name: copy script files
  ansible.builtin.copy:
    src: "{{ dir.src }}"
    dest: "{{ dir.dest }}"
    owner: "{{ main_user.name }}"
    group: "{{ main_user.name }}"
    mode: "{{ dir.mode }}"
  loop:
    - { src: 'scripts/', dest: '{{ directories.scripts }}/', mode: '0755' }
    - { src: 'shared/', dest: '{{ directories.scripts }}/shared/', mode: '0644' }
  loop_control:
    loop_var: dir

- name: pull an alpine image
  community.docker.docker_image_pull:
    name: alpine

- name: deploy docker backup service and timer
  ansible.builtin.template:
    src: "{{ filename }}.j2"
    dest: "/etc/systemd/system/{{ filename }}"
    owner: root
    group: root
    mode: 0644
  notify: reload_systemd
  loop:
    - docker-backup.service
    - docker-backup.timer
  loop_control:
    loop_var: filename

- name: start and enable docker backup timer
  systemd:
    name: docker-backup.timer
    enabled: yes
    state: started
