- name: ensure volumes backup directory exists
  ansible.builtin.file:
    path: "{{ directories.backup }}/volumes"
    state: directory
    owner: "{{ main_user.name }}"
    group: "{{ main_user.name }}"
    mode: 0755

- name: copy exec scripts to bin directory
  ansible.builtin.copy:
    src: scripts/
    dest: "{{ directories.scripts }}/"
    owner: "{{ main_user.name }}"
    group: "{{ main_user.name }}"
    mode: 0755

- name: copy helper files (non-exec) to scripts/shared directory
  ansible.builtin.copy:
    src: shared/
    dest: "{{ directories.scripts }}/shared/"
    owner: "{{ main_user.name }}"
    group: "{{ main_user.name }}"
    mode: 0644

- name: pull an alpine image
  community.docker.docker_image_pull:
    name: alpine

- name: deploy docker backup service
  ansible.builtin.template:
    src: docker-backup.service.j2
    dest: /etc/systemd/system/docker-backup.service
    owner: root
    group: root
    mode: 0644
  notify: reload_systemd

- name: deploy docker backup timer
  ansible.builtin.template:
    src: docker-backup.timer.j2
    dest: /etc/systemd/system/docker-backup.timer
    owner: root
    group: root
    mode: 0644
  notify: reload_systemd

- name: enable and start docker backup timer
  systemd:
    name: docker-backup.timer
    enabled: yes
    state: started
