backup_volumes_dir: "{{ directories.backup }}/volumes"

backup_retention_period: 14

backup_schedule: "*-*-* 04:30:00"

backup_service_timeout: 45m

backup_exclude_volumes:
  - homepage_*_data
  - traefik_data
  - gluetun_data
