- name: stop and remove portainer container, volume and image
  community.docker.docker_compose_v2:
    project_src: "{{ directories.services }}/portainer"
    state: absent
    remove_images: all
    remove_volumes: true
  ignore_errors: true

- name: delete portainer directory
  ansible.builtin.file:
    path: "{{ directories.services }}/portainer"
    state: absent
  ignore_errors: true
