- name: stop and remove code-server container, volumes and image
  community.docker.docker_compose_v2:
    project_src: "{{ directories.services }}/code-server"
    state: absent
    remove_images: all
    remove_volumes: true
  ignore_errors: true

- name: delete code-server directory
  ansible.builtin.file:
    path: "{{ directories.services }}/code-server"
    state: absent
  ignore_errors: true
