- name: setup code-server service and workspace directories
  ansible.builtin.file:
    path: "{{ path }}"
    state: directory
    owner: "{{ main_user.name }}"
    group: "{{ main_user.name }}"
    mode: 0755
  loop:
    - "{{ directories.services }}/code-server"
    - "{{ directories.storage }}/workspace"
  loop_control:
    loop_var: path

- name: set env variable for workspace directory
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: '^WORKSPACE_DIR='
    line: "WORKSPACE_DIR={{ directories.storage }}/workspace"
    state: present
    create: yes

- name: deploy code-server from template files
  ansible.builtin.template:
    src: "templates/{{ filename }}.j2"
    dest: "{{ directories.services }}/code-server/{{ filename }}"
    owner: "{{ main_user.name }}"
    group: "{{ main_user.name }}"
    mode: 0644
  loop:
    - Dockerfile
    - docker-compose.yml
  loop_control:
    loop_var: filename

- name: run code-server using docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ directories.services }}/code-server"
    build: always
