code_server:
  version: 4.102.3
  host: "{{ vault_code_host }}"
  port: "{{ vault_code_port }}"
  password: "{{ vault_code_password }}"
  sudo_password: "{{ vault_code_sudo_password }}"
  docker_gid: "{{ vault_docker_guid }}"
  home: /config
  workspace:
    src: "{{ directories.storage }}/workspace"
    dest: /workspace
  git:
    username: "{{ vault_code_git_username }}"
    email: "{{ vault_code_git_email }}"
