portainer:
  version: 2.32.0
  host: "{{ vault_portainer_host }}"
  port: "{{ vault_portainer_port }}"
  homepage:
    name: Portainer
    description: Docker Manager
    icon: /icons/portainer.png
    group: System
    env: 3
    token: "{{ vault_portainer_homepage_token }}"
    weight: 2
