- name: stop and remove cloudflared container, volumes and image
  community.docker.docker_compose_v2:
    project_src: "{{ directories.services }}/cloudflared"
    state: absent
    remove_images: all
  ignore_errors: true

- name: delete cloudflared directory
  ansible.builtin.file:
    path: "{{ directories.services }}/cloudflared"
    state: absent
  ignore_errors: true
