vaultwarden:
  version: latest
  host: "{{ vault_vaultwarden_host }}"
  port: "{{ vault_vaultwarden_port }}"
  homepage:
    title: Vaultwarden
    description: Password Manager
    icon: /icons/vaultwarden.png
    group: Utils
    order: 2
