speedtest:
  version: 1.6.6
  host: "{{ vault_speedtest_host }}"
  port: "{{ vault_speedtest_port }}"
  app_key: "{{ vault_speedtest_app_key }}"
  servers: "{{ vault_speedtest_servers }}"
  admin:
    email: "{{ vault_speedtest_admin_email }}"
    password: "{{ vault_speedtest_admin_password }}"
