speedtest:
  version: 1.6.6
  host: "{{ vault_speedtest_host }}"
  port: "{{ vault_speedtest_port }}"
  db: sqlite
  dashboard: true
  servers: "{{ vault_speedtest_servers }}"
  schedule: "6 */2 * * *"
  prune_days: 30
  app:
    name: 'Speedtest Tracker'
    key: "{{ vault_speedtest_app_key }}"
  admin:
    email: "{{ vault_admin_email }}"
    password: "{{ vault_admin_password }}"
  homepage:
    name: Speedtest
    description: Speed Test Tracker
    icon: /icons/speedtest.png
    group: System
    bitratePrecision: 0
    weight: 1
