cloudflared:
  version: 2025.8.0
  account_id: "{{ vault_account_id }}"
  tunnel:
    id: "{{ vault_tunnel_id }}"
    token: "{{ vault_tunnel_token }}"
  homepage:
    name: Cloudflared
    description: Cloudflare Tunnel
    icon: /icons/cloudflare.png
    group: System
    url: https://dash.cloudflare.com
    token: "{{ vault_homepage_token }}"
    weight: 3
