ansible_host: "{{ vault_ansible_host }}"

main_user: 
  name: "{{ vault_main_user_name }}"
  uid: "{{ vault_main_user_uid }}"
  gid: "{{ vault_main_user_gid }}"

ssh_users: "{{ main_user.name }} {{ ansible_username }}"
ssh_template_file: sshd_config_ubuntu.j2

dns_resolver_1: "{{ vault_dns_resolver_1 }}"
dns_resolver_2: "{{ vault_dns_resolver_2 }}"

local_dns_internal_ip: "{{ vault_local_dns_internal_ip }}"

drives:
  system:
    device: "{{ vault_system_drive_device }}"
    filesystem: lvm
    logical_volume:
      name: "{{ vault_system_drive_lv_name }}"
      group: "{{ vault_system_drive_vg_name }}"
      size: all
  additional:
    - id: storage
      label: "{{ vault_storage_drive_label }}"
      device: "{{ vault_storage_drive_device }}"
      mount_point: "{{ vault_storage_drive_mount_point }}"
      filesystem: ext4
    - id: media_1
      label: "{{ vault_media_1_drive_label }}"
      device: "{{ vault_media_1_drive_device }}"
      mount_point: "{{ vault_media_1_drive_mount_point }}"
      filesystem: ntfs-3g
    - id: media_2
      label: "{{ vault_media_2_drive_label }}"
      device: "{{ vault_media_2_drive_device }}"
      mount_point: "{{ vault_media_2_drive_mount_point }}"
      filesystem: ntfs-3g

directories:
  home: "/home/{{ main_user.name }}"
  services: "/home/{{ main_user.name }}/services"
  scripts: "/usr/local/bin"
  storage: "{{ drives.additional | selectattr('id', 'equalto', 'storage') | map(attribute='mount_point') | first }}/data"
  backup: "{{ drives.additional | selectattr('id', 'equalto', 'storage') | map(attribute='mount_point') | first }}/data/backup"
  media_1: "{{ drives.additional | selectattr('id', 'equalto', 'media_1') | map(attribute='mount_point') | first }}/data_1"
  media_2: "{{ drives.additional | selectattr('id', 'equalto', 'media_2') | map(attribute='mount_point') | first }}/data_2"
