netplan_filename: 50-cloud-init.yaml

proxy_local_hostname: "{{ vault_proxy_local_hostname }}"

pihole:
  version: 2025.03.0
  host: "{{ vault_pihole_host }}"
  password: "{{ vault_pihole_password }}"
  app_pass: "{{ vault_pihole_app_pass }}"
  dns_records:
    - "{{ ansible_host }} {{ proxy_local_hostname }}"
    - "{{ vault_router_ip }} {{ vault_router_local_hostname }}"
  cname_records:
    - "{{ vault_pihole_host }},{{ proxy_local_hostname }}"
    - "{{ vault_proxy_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_portainer_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_system_monitor_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_admin_dashboard_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_public_dashboard_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_nodered_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_code_server_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_speedtest_tracker_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_password_manager_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_plex_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_radarr_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_sonarr_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_bazarr_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_qbittorrent_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_prowlarr_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_youtube_downloader_public_hostname }},{{ proxy_local_hostname }}"
