netplan_filename: 50-cloud-init.yaml

local_dns_internal_ip: "{{ vault_local_dns_internal_ip }}"

proxy_local_hostname: "{{ vault_proxy_local_hostname }}"

pihole:
  version: 2025.03.0
  host: "{{ vault_pihole_host }}"
  password: "{{ vault_pihole_password }}"
  dns_records:
    - "{{ ansible_host }} {{ proxy_local_hostname }}"
    - "{{ vault_router_ip }} {{ vault_router_local_hostname }}"
  cname_records:
    - "{{ vault_pihole_host }},{{ proxy_local_hostname }}"
    - "{{ vault_proxy_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_portainer_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_code_server_public_hostname }},{{ proxy_local_hostname }}"
    - "{{ vault_speedtest_tracker_public_hostname }},{{ proxy_local_hostname }}"
