glances:
  version: 4.3.3
  host: "{{ vault_glances_host }}"
  port: "{{ vault_glances_port }}"
  homepage:
    title: Glances
    description: See More
    icon: /icons/glances.png
    group: Performance
    order: 700
